### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by unitedworx**
make this work with elixir 3 since extensions will need to be updated to support version 3.0.
https://github.com/laravel/elixir/releases

Maybe you could update the version on this extension to allow people to keep using the older version for elixir 2!

### CODE REVIEW

**Comment by marcin-derlukiewicz** [comment]
works, pls apply

**Comment by EHLOVader** [comment]
This will break the package for users still on Elixir 2.x without a major version bump at least. But I would recommend using `peerDependencies` as well and keeping a release branch for Elixir 2.x as you move forward to 3.x and the newer API. 

`peerDependencies` won't install the dependency but will error if the proper dependency isn't met. You can see how I managed it in my [laravel-elixir-livereload](https://github.com/EHLOVader/laravel-elixir-livereload/blob/master/package.json#L33) package.

**Comment by unitedworx** [comment]
Thanks for the advice @EHLOVader !!! Just added elixir 3.x as per your advice!

@farrrr can you pull this in pls?

**Comment by EHLOVader** [comment]
I don't think github has a way to handle PRs for branches other than master but @farrrr will want to create a 2.x branch with peerDependencies set appropriately.

I also didn't know if you are saving the major version bump for PR acceptance but it will be important so users can use ^1.0 for Elixir 2.x and ^2.0 for Elixir 3.0

I first pinned the version I was on to Elixir 2.x with peerDependencies then made a branch from that master. Then I bumped the versions in the peer dependency and my own package to move master to Elixir 3.x.

I should really blog the process.

**Comment by farrrr** [comment]
thanks for your contribution, I have already published the new version.

Thanks for your advice.

**Comment by EHLOVader** [comment]
Fair warning though.

Since you only bumped the patch version it may still cause problems for users on Elixir 2, unless they set the version specifically to 1.0.2. 

Sorry I missed that point in the first comment.
More on [semver here](https://docs.npmjs.com/misc/semver)

**Comment by farrrr** [comment]
@EHLOVader I create 2 tags. 2.0.0 for Elixir 2 and create npm version 2.0.0. and 3.0.0 for Elixir 3, and follow your repo update my readme. Is it correct?

**Comment by EHLOVader** [comment]
maybe it does work that way @farrrr, I thought it also relied on the contents of your package.json which wasn't bumped to match the tags. 

But NPM has it listed right. So I am probably wrong.

**Comment by farrrr** [comment]
@EHLOVader yep, npm just relied on the version in package.json. I create 2 tags just for me to identify.

**Pull request merged**
